### ISSUE TITLE
Have some way to configure what database it uses

### ISSUE THREAD

**Issue by jeffbaumes** [arborworkflows/ProjectManager#4]
Would be nice if hostname and db were somehow configured (maybe json file?). Right now they are hardcoded in the python code.

**Comment by curtislisle** [comment]
API now supports changes to the database.  See calls 'setMongoDatabase()', setPrefixString(), and 'initDatabaseConnection'.  This still is assumed to be on localhost, but all dynamic update machinery has been implemented.  Still uses connection, which is deprecated, but is working now.
